import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1 className='text-4xl text-red-600'>Home</h1>
      </main>
    </>
  )
}
